

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

# [[plugins]]
# repo = 'dag/vim-fish'
# on_ft = ['fish']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# [[plugins]]
# repo = 'Shougo/neoinclude.vim'
# on_ft = ['c', 'cpp']
# depends = ['deoplete.nvim']

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_source = '''
	nmap <silent> <leader>mw :A<CR>
	nmap <silent> <leader>mt :AT<CR>
	nmap <silent> <leader>mv :AV<CR>
'''

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp']
hook_source = '''
	nmap <leader>dox :Dox<CR>
'''

