

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

# [[plugins]]
# repo = 'dag/vim-fish'
# on_ft = ['fish']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# [[plugins]]
# repo = 'Shougo/neoinclude.vim'
# on_ft = ['c', 'cpp']
# depends = ['deoplete.nvim']

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_source = '''
	nmap <silent> <leader>mw :A<CR>
	nmap <silent> <leader>mt :AT<CR>
	nmap <silent> <leader>mv :AV<CR>
'''

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp']
hook_source = '''
	nmap <leader>dox :Dox<CR>
'''


# 動かすと多重に動くせいかカッコ表示が激烈遅くなる
# [[plugins]]
# repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'neovim/python-client'
if = '''!has('nvim')'''


[[plugins]]
repo = 'mattesgroeger/vim-bookmarks'
hook_add = '''
	source ~/.config/nvim/plugins/bookmark.vim
'''

# [[plugins]]
# repo = 'scrooloose/nerdcommenter'
# hook_add = '''
#     source ~/.config/nvim/plugins/nerdcommenter.vim
# '''

# 特定のファイルタイプでハイライトが効果がなくなったりするらしく悩ましい
# 余計なことをするとすごく後で悩む可能性が。
# [[plugins]]
# repo = 'Yggdroot/indentLine'
# hook_add = '''
#     let g:indentLine_enabled = 1
#     let g:indentLine_char_list = ['|', '¦', '┆', '┊']
#     let g:indentLine_defaultGroup = 'SpecialKey'
#     set list listchars=tab:\¦\
# '''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
	xmap ga <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'

